#ifndef JURACONFIGURATION_H
#define JURACONFIGURATION_H
#include "JuraEnums.h"

/* debugging and ressearch feature flags */
#define PRINT_UNHANDLED    false    /* print values that aren't curerntly captured; for investigation of new values and when they change*/
#define PRINT_KNOWN_VALUES false    /* for debugging, print captured values when recognized andupdated */

/* ESP */
#define BRIDGE_NAME       "Jura Bridge"
#define CONTROLLER_NAME   "Jura Controller"
#define THERMOBLOCK_NAME  "Jura Thermoblock"
#define BREW_GROUP_NAME   "Jura Brew Group"
#define WATER_NAME        "Jura Water System"
#define DOSING_NAME       "Jura Dosing System"
#define MILKSYSTEM_NAME   "Jura Milk System"

#define MQTT_ROOT     "jurabridge"
#define NAME_PREFIX   ""      /* trailing space strongly recommended if used */
#define ENTITY_PREFIX ""      /* trailing underscore required if used */
#define PREF_PREFIX   "PREF"
#define MANUFACTURER  "Andrew J Freyer"
#define MODEL_NUM     "jurabridge for Jura ENA Micro 90"
#define TAG           "jb"

/* jura service port and hardware interface configuration */
#define DEV_BOARD_ID                            "ESP32 Dev Module"
#define DEV_BOARD_UART_ID                       2
#define DEV_BOARD_LED_PIN                       2
#define DEV_BOARD_BUTTON_PIN                    21
#define DEV_BOARD_UART_RX_PIN                   16
#define DEV_BOARD_UART_TX_PIN                   17
#define DEV_BOARD_UART_TIMEOUT                  300

/* timeout values for force refresh */
#define JURA_MACHINE_EEPROM_TIMEOUT             3000000
#define JURA_MACHINE_INPUT_BOARD_TIMEOUT        3000000
#define JURA_MACHINE_HEATED_BEVERAGE_TIMEOUT    3000000
#define JURA_MACHINE_SYSTEM_CIRCUITRY_TIMEOUT   10000

/* timeout values for calculated properties */ 
#define JURA_MACHINE_BEANS_REFILLED_TIMEOUT           5000

/* timeouts for machine operations */
#define JURA_MACHINE_AWAIT_NEXT_INSTRUCTION_TIMEOUT_S 120
#define JURA_MACHINE_AUTOMATIC_MAINTENANCE_TIMEOUT_S  120
#define JURA_MACHINE_AUTOMATIC_MILK_RINSE_TIMEOUT_S   150
#define JURA_MACHINE_AUTOMATIC_DISPENSE_LIMIT_TIMEOUT_S 90
#define JURA_MACHINE_AUTOMATIC_BREW_GROUP_RINSE_TIMEOUT_S 300

/* preference keys */
#define PREF_KEY                                "jb"

/* temperature thresholds */
#define COLD_MODE_THRESHOLD                     60
#define LOW_MODE_THRESHOLD                      96
#define HIGH_MODE_THRESHOLD                     104
#define OVERTEMP_THRESHOLD                      115
#define SANITATION_TEMP_THRESHOLD               148 /* for milk clean; required temperature is 150, so 2deg buffer*/

/* constants */
#define JURA_MACHINE_BEAN_HOPPER_CAPACITY_G      200
#define JURA_MACHINE_DRIP_TRAY_CAPACITY_ML       500 /* actual drip tray capacity measured at 500ml, but it appears warnings trigger at 250 or so*/
#define JURA_MACHINE_WATER_RESERVOIR_CAPACITY_ML 1000
#define DEFAULT_DRAINAGE_ML                      25
#define RINSE_BREW_GROUP_DRAINAGE                50
#define RINSE_MILK_SYSTEM_DRAINAGE               60
#define BREW_GROUP_CLEAN_THRESHOLD               130
#define BREW_GROUP_CLEAN_RECOMMEND_THRESHOLD     100
/* 
pumped water volume will vary vary each dispense type; excess will remain in the machine or will 
be dumped to the drainage tray (e.g., condenser, drainage valve, etc). the following are approximations;  
*/
#define DISPENSED_ML_CALIBRATION_COEFFICIENT_DEFAULT   0.5        /* 0.46391753 dispensed 90 ml when 194 was reported; 0.5 presumes 0.5ml for every spin of the flow meter */
#define DISPENSED_ML_CALIBRATION_COEFFICIENT_COFFEE    0.44978166 /* dispensed 206 ml when 458 was reported */
#define DISPENSED_ML_CALIBRATION_COEFFICIENT_ESPRESSO  0.35802469 /* dispensed 29 ml when 81 was reported */
#define DISPENSED_ML_CALIBRATION_COEFFICIENT_MILK      2.17543860  /* dispensed 124 ml when 57 was reported */
#define DISPENSED_ML_CALIBRATION_COEFFICIENT_OATMILK   2.08196721  /* dispensed 127 ml when 61 was reported */

#define BUTTON_HOLD_DURATION_MS                 750
/*

  name:         JuraEntityConfigurations
  type:         array
  description:  this array contains instances of JuraEntityConfiguration; 
                indexes of this array are used to store values in caches for machine instance
                and bridge instance. 

*/

/*

    NOTE: THE MORE OF THESE THAT ARE ENABLED AND ARE REPORTING, THE SLOWER THE ENTIRE SYSTEM 
    WILL BE, INCLUDING TO RESPOND TO MQTT INSTRUCTIONS FROM HA OR ANOTHER CONTROLLER. STRONGLY RECOMMEND 
    DISABLING MANY OF THE SENSORS IF THEY'RE NOT NEEDED IN HOME AUTOMATION PLATFORMS.

*/

static const JuraEntityConfiguration JuraEntityConfigurations[] = {
  /* this is used for last will messages as well, so keep it at index zero */
  {
    JuraMachineStateIdentifier::OperationalState, 
    NAME_PREFIX "Operational State",
    ENTITY_PREFIX "operational_state",
    JuraMachineStateDataType::String,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Info,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::No,
  },
  {
    JuraMachineStateIdentifier::ReadyStateDetail, 
    NAME_PREFIX "Ready State Detail",
    ENTITY_PREFIX "ready_state_detail",
    JuraMachineStateDataType::String,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Info,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::No,
  },
  {
    JuraMachineStateIdentifier::NumEspresso, 
    NAME_PREFIX "Espresso",
    ENTITY_PREFIX "espresso",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Preparation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumCoffee,
    NAME_PREFIX "Coffee",
    ENTITY_PREFIX "coffee",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Preparation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumCappuccino,
    NAME_PREFIX "Cappuccino",
    ENTITY_PREFIX "cappuccino",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Preparation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumMacchiato,
    NAME_PREFIX "Macchiato",
    ENTITY_PREFIX "macchiato",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Preparation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumPreground,
    NAME_PREFIX "Preground",
    ENTITY_PREFIX "preground",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Preparation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumDriveMotorOperations,
    NAME_PREFIX "Drive Motor Operations",
    ENTITY_PREFIX "drive_motor_operations",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Operation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumLowPressurePumpOperations,
    NAME_PREFIX "Low Pressure",
    ENTITY_PREFIX "low_pressure",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Operation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumBrewGroupCleanOperations,
    NAME_PREFIX "Cleanings of Brew Group",
    ENTITY_PREFIX "cleans_brew_group",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Operation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumSpentGrounds,
    NAME_PREFIX "Spent Grounds",
    ENTITY_PREFIX "spent_grounds",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Dose,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::SpentGroundsLevel,
    NAME_PREFIX "Knockbox Fill Level",
    ENTITY_PREFIX "knockbox_fill_level",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Percent,
    JuraEntityEnabled::Yes, 
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumPreparationsSinceLastBrewGroupClean,
    NAME_PREFIX "Since Clean",
    ENTITY_PREFIX "since_clean",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Preparation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumHighPressurePumpOperations,
    NAME_PREFIX "High Pressure",
    ENTITY_PREFIX "high_pressure",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Operation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumMilkFoamPreparations,
    NAME_PREFIX "Milk Foam",
    ENTITY_PREFIX "milk_foam",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Coffee,
    JuraMachineStateUnit::Operation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Milksystem,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumWaterPreparations,
    NAME_PREFIX "Hot Water",
    ENTITY_PREFIX "hot_water",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Water,
    JuraMachineStateUnit::Preparation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumGrinderOperations,
    NAME_PREFIX "Grindings",
    ENTITY_PREFIX "grindings",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Cycle,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::NumCleanMilkSystemOperations,
    NAME_PREFIX "Cleanings of Milk System",
    ENTITY_PREFIX "cleans_milk_system",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::Operation,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::MeterValue,
    JuraMachineSubsystem::Milksystem,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::HasFilter,
    NAME_PREFIX "Water Filter",
    ENTITY_PREFIX "water_filter",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BeanHopperEmpty,
    NAME_PREFIX "Bean Hopper Empty",
    ENTITY_PREFIX "bean_hopper_empty",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Opening,
    JuraMachineStateIcon::Alert,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BeanHopperCoverOpen,
    NAME_PREFIX "Bean Hopper Open",
    ENTITY_PREFIX "bean_hopper_open",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Opening,
    JuraMachineStateIcon::Alert,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::SpentBeansByWeight,
    NAME_PREFIX "Beans Consumed",
    ENTITY_PREFIX "beans_consumed",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Coffee,
    JuraMachineStateUnit::Grams,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::DataValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BeanHopperLevel,
    NAME_PREFIX "Bean Hopper Fill Level",
    ENTITY_PREFIX "bean_hopper_fill_level",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Coffee,
    JuraMachineStateUnit::Percent,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::DataValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::WaterReservoirNeedsFill,
    NAME_PREFIX "Water Reservoir",
    ENTITY_PREFIX "fill_water_reservoir",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Problem,
    JuraMachineStateIcon::Alert,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BypassDoserCoverOpen,
    NAME_PREFIX "Bypass Doser Open",
    ENTITY_PREFIX "bypass_doser_open",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Opening,
    JuraMachineStateIcon::Alert,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::DrainageTrayRemoved,
    NAME_PREFIX "Drip Tray Removed",
    ENTITY_PREFIX "drip_tray_removed",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Opening,
    JuraMachineStateIcon::Alert,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::DrainageTrayFull,
    NAME_PREFIX "Drip Tray Full",
    ENTITY_PREFIX "drip_tray_full",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Problem,
    JuraMachineStateIcon::Alert,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::Error,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::DrainageTrayLevel,
    NAME_PREFIX "Drip Tray Level",
    ENTITY_PREFIX "drip_tray_level",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Alert,
    JuraMachineStateUnit::Percent,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::DrainageSinceLastTrayEmpty,
    NAME_PREFIX "Drainage Volume",
    ENTITY_PREFIX "drainage_volume",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Alert,
    JuraMachineStateUnit::Milliliters,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::FlowState,
    NAME_PREFIX "Flow State",
    ENTITY_PREFIX "flow_state",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Running,
    JuraMachineStateIcon::Function,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewGroupPosition,
    NAME_PREFIX "Brew Group Position",
    ENTITY_PREFIX "brew_group_position",
    JuraMachineStateDataType::String,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewGroupDriveShaftPosition,
    NAME_PREFIX "Brew Group Drive Shaft Position",
    ENTITY_PREFIX "brew_group_drive_shaft_position",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Running,
    JuraMachineStateIcon::Function,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No, /*  will rapidly change value when brew_group is moving; reocmmend disable*/
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewGroupEncoderState,
    NAME_PREFIX "Brew Group Encoder State",
    ENTITY_PREFIX "brew_group_encoder_state",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Running,
    JuraMachineStateIcon::Function,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No, /* encoder will rapidly change value when brew_group is moving; reocmmend disable*/
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::OutputValveEncoderState,
    NAME_PREFIX "Output Valve Encoder State",
    ENTITY_PREFIX "output_valve_encoder_state",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Running,
    JuraMachineStateIcon::Function,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No, /* encoder will rapidly change value when output valve is moving; reocmmend disable */ 
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::OutputValveNominalPosition,
    NAME_PREFIX "Output Valve Nominal",
    ENTITY_PREFIX "output_valve_nominal",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Function,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::HasError,
    NAME_PREFIX "Error",
    ENTITY_PREFIX "error",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Problem,
    JuraMachineStateIcon::Alert,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::HasMaintenanceRecommendation,
    NAME_PREFIX "Maintenance Recommendation",
    ENTITY_PREFIX "maintenance_recommendation",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::Problem,
    JuraMachineStateIcon::Alert,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::RinseBrewGroupRecommended,
    NAME_PREFIX "Water Rinse Recommended",
    ENTITY_PREFIX "rinse_brew_group_recommended",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::ServiceRecommendation,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockPreheated,
    NAME_PREFIX "Thermoblock Preheated",
    ENTITY_PREFIX "thermoblock_preheated",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Thermometer,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockReady,
    NAME_PREFIX "Thermoblock Ready",
    ENTITY_PREFIX "thermoblock_ready",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::OutputValvePosition,
    NAME_PREFIX "Output Valve Position",
    ENTITY_PREFIX "output_valve_position",
    JuraMachineStateDataType::String,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::OutputValveIsBrewing,
    NAME_PREFIX "Output Valve Brewing Position",
    ENTITY_PREFIX "output_valve_brewing_position",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::OutputValveIsFlushing,
    NAME_PREFIX "Output Valve Flushing Position",
    ENTITY_PREFIX "output_valve_flushing_position",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::OutputValveIsDraining,
    NAME_PREFIX "Output Valve Draining Position",
    ENTITY_PREFIX "output_valve_draining_position",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::OutputValveIsBlocking,
    NAME_PREFIX "Output Valve Blocking Position",
    ENTITY_PREFIX "output_valve_blocking_position",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::WaterPumpFlowRate,
    NAME_PREFIX "Flow Rate",
    ENTITY_PREFIX "flow_rate",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::MicrolitersPerSecond,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::LastDispensePumpedWaterVolume,
    NAME_PREFIX "Last Dispense Pumped Water Volume",
    ENTITY_PREFIX "last_dispense_pumped_water_volume",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::Milliliters,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::LastMilkDispenseVolume,
    NAME_PREFIX "Last Milk Dispense Volume",
    ENTITY_PREFIX "last_milk_dispense_volume",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::Milliliters,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Milksystem,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::LastWaterDispenseVolume,
    NAME_PREFIX "Last Water Dispense Volume",
    ENTITY_PREFIX "last_water_dispense_volume",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::Milliliters,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::LastBrewDispenseVolume,
    NAME_PREFIX "Last Brew Dispense Volume",
    ENTITY_PREFIX "last_brew_dispense_volume",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::Milliliters,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  }, 
  {
    JuraMachineStateIdentifier::LastDispenseMaxTemperature,
    NAME_PREFIX "Last Dispense Max Temperature",
    ENTITY_PREFIX "last_dispense_max_temperature",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::Celcius,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::LastDispenseType,
    NAME_PREFIX "Last Dispense Type",
    ENTITY_PREFIX "last_dispense_type",
    JuraMachineStateDataType::String,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Thermometer,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },      
  {
    JuraMachineStateIdentifier::LastDispenseGrossTemperatureTrend,
    NAME_PREFIX "Last Dispense Gross Temperature Trend",
    ENTITY_PREFIX "last_dispense_gross_temperature_trend",
    JuraMachineStateDataType::String,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Thermometer,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },  
  {
    JuraMachineStateIdentifier::LastDispenseDuration,
    NAME_PREFIX "Last Dispense Duration",
    ENTITY_PREFIX "last_dispense_duration",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::Seconds,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::LastDispenseMinTemperature,
    NAME_PREFIX "Last Dispense Min Temperature",
    ENTITY_PREFIX "last_dispense_in_temperature",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::Celcius,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::LastDispenseAvgTemperature,
    NAME_PREFIX "Last Dispense Average Tempreature",
    ENTITY_PREFIX "last_dispense_average_temperature",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::Celcius,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockTemperature,
    NAME_PREFIX "Thermoblock Temperature",
    ENTITY_PREFIX "thermoblock_temperature",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Thermometer,
    JuraMachineStateUnit::Celcius,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockStatus,
    NAME_PREFIX "Thermoblock Status",
    ENTITY_PREFIX "thermoblock_status",
    JuraMachineStateDataType::String,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Thermometer,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockColdMode,
    NAME_PREFIX "Cold Temperature",
    ENTITY_PREFIX "cold_temperature",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Thermometer,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockLowMode,
    NAME_PREFIX "Low Temperature",
    ENTITY_PREFIX "low_temperature",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Thermometer,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockHighMode,
    NAME_PREFIX "High Temperature",
    ENTITY_PREFIX "high_temperature",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Thermometer,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockOvertemperature,
    NAME_PREFIX "Overtemperture",
    ENTITY_PREFIX "overtemperture",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Thermometer,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockSanitationTemperature,
    NAME_PREFIX "Sanitation",
    ENTITY_PREFIX "sanitation",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Thermometer,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::SystemWaterMode,
    NAME_PREFIX "Hot Water Mode",
    ENTITY_PREFIX "hot_water_mode",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::SystemSteamMode,
    NAME_PREFIX "Steam Mode",
    ENTITY_PREFIX "steam_mode",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewGroupLastOperation, 
    NAME_PREFIX "Last Brew Group Operation",
    ENTITY_PREFIX "last_brew_group_operation",
    JuraMachineStateDataType::String,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::DataValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::CeramicValvePosition,
    NAME_PREFIX "Ceramic Valve Position",
    ENTITY_PREFIX "ceramic_valve_position",
    JuraMachineStateDataType::String,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::CeramicValveCondenserPosition,
    NAME_PREFIX "Ceramic Valve Condenser Position",
    ENTITY_PREFIX "ceramic_valve_condenser_position",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::CeramicValveHotWaterPosition,
    NAME_PREFIX "Ceramic Valve Hot Water Position",
    ENTITY_PREFIX "ceramic_valve_hot_water_position",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::CeramicValvePressurizingPosition,
    NAME_PREFIX "Ceramic Valve Pressurizing Position",
    ENTITY_PREFIX "ceramic_valve_pressurizing_position",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::CeramicValveBrewingPosition,
    NAME_PREFIX "Ceramic Valve Brewing Position",
    ENTITY_PREFIX "ceramic_valve_brewing_position",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::CeramicValveSteamPosition,
    NAME_PREFIX "Ceramic Valve Steam Position",
    ENTITY_PREFIX "ceramic_valve_steam_position",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::CeramicValveVenturiPosition,
    NAME_PREFIX "Ceramic Valve Venturi Position",
    ENTITY_PREFIX "ceramic_valve_venturi_position",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::CeramicValvePressureReliefPosition,
    NAME_PREFIX "Ceramic Valve Pressure Relief Position",
    ENTITY_PREFIX "ceramic_valve_pressure_relief_position",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Valve,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockMilkDispenseMode,
    NAME_PREFIX "Thermoblock Milk Dispense Mode",
    ENTITY_PREFIX "thermoblock_milk_dispense",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::Running,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::VenturiPumping,
    NAME_PREFIX "Venturi Pumping",
    ENTITY_PREFIX "venturi_pumping",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::Running,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockDutyCycle,
    NAME_PREFIX "Thermoblock Duty Cycle",
    ENTITY_PREFIX "thermoblock_duty_cycle",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Speedometer,
    JuraMachineStateUnit::Percent,
    JuraEntityEnabled::No, /* will rapidly change, but appears to be close to 100% most of the time */
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::ThermoblockActive,
    NAME_PREFIX "Thermoblock Active",
    ENTITY_PREFIX "thermoblock_active",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::PumpDutyCycle,
    NAME_PREFIX "Pump Duty Cycle",
    ENTITY_PREFIX "pump_duty_cycle",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Speedometer,
    JuraMachineStateUnit::Percent,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::PumpActive,
    NAME_PREFIX "Pump Active",
    ENTITY_PREFIX "pump_active",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Water,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::GrinderDutyCycle,
    NAME_PREFIX "Grinder Duty Cycle",
    ENTITY_PREFIX "grinder_duty_cycle",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Speedometer,
    JuraMachineStateUnit::Percent,
    JuraEntityEnabled::No, /* changes rapidly but doesnot appear to vary */
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::GrinderActive,
    NAME_PREFIX "Grinder Active",
    ENTITY_PREFIX "grinder_active",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewGroupDutyCycle,
    NAME_PREFIX "Brew Group Duty Cycle",
    ENTITY_PREFIX "brew_group_duty_cycle",
    JuraMachineStateDataType::Integer,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Speedometer,
    JuraMachineStateUnit::Percent,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewGroupActive,
    NAME_PREFIX "Brew Group Active",
    ENTITY_PREFIX "brew_group_active",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewGroupIsRinsing,
    NAME_PREFIX "Brew Group Rinsing",
    ENTITY_PREFIX "brew_group_rinsing",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewGroupIsReady,
    NAME_PREFIX "Brew Group Ready",
    ENTITY_PREFIX "brew_group_ready",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    1 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewGroupIsLocked,
    NAME_PREFIX "Brew Group Locked",
    ENTITY_PREFIX "brew_group_locked",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewGroupIsOpen,
    NAME_PREFIX "Brew Group Open",
    ENTITY_PREFIX "brew_group_open",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::BrewGroup,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewProgramIsReady,
    NAME_PREFIX "Brew Program Ready",
    ENTITY_PREFIX "brew_program_ready",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::BrewProgramIsCleaning,
    NAME_PREFIX "Tablet Cleaning",
    ENTITY_PREFIX "tablet_cleaning",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Diagnostic,
    JuraMachineDeviceClass::Running,
    JuraMachineStateIcon::Counter,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::GroundsNeedsEmpty,
    NAME_PREFIX "Grounds Needs Empty",
    ENTITY_PREFIX "grounds_needs_empty",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Alert,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::SystemIsReady,
    NAME_PREFIX "System Ready",
    ENTITY_PREFIX "system_ready",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::RinseMilkSystemRecommended,
    NAME_PREFIX "Milk Rinse Recommended",
    ENTITY_PREFIX "rinse_milk_system_recommended",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::ServiceRecommendation,
    JuraMachineSubsystem::Milksystem,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::CleanMilkSystemRecommended,
    NAME_PREFIX "Milk Clean Recommended",
    ENTITY_PREFIX "clean_milk_system_recommended",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::ServiceRecommendation,
    JuraMachineSubsystem::Milksystem,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::CleanBrewGroupRecommendedSoon,
    NAME_PREFIX "System Clean Recommended",
    ENTITY_PREFIX "clean_brew_group_recommended",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::ServiceRecommendation,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::CleanBrewGroupRecommended,
    NAME_PREFIX "System Clean Required",
    ENTITY_PREFIX "clean_system_required",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::ServiceRecommendation,
    JuraMachineSubsystem::Controller,
    JuraEntityNonvolatile::Yes,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::HasDose,
    NAME_PREFIX "Dose in Brew Group",
    ENTITY_PREFIX "dose_in_brew_group",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::StateValue,
    JuraMachineSubsystem::Dosing,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::PurgeWaterOperationRecommended,
    NAME_PREFIX "Normalize Thermoblock Temperature Recommended",
    ENTITY_PREFIX "normalize_thermoblock_temperature_recommended",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::ServiceRecommendation,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::OverextractionLikely,
    NAME_PREFIX "Overextraction Risk",
    ENTITY_PREFIX "overextraction_risk",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::ServiceRecommendation,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  },
  {
    JuraMachineStateIdentifier::UnderextractionLikely,
    NAME_PREFIX "Underextraction Risk",
    ENTITY_PREFIX "underextraction_risk",
    JuraMachineStateDataType::Boolean,
    JuraMachineStateCategory::Config,
    JuraMachineDeviceClass::None,
    JuraMachineStateIcon::Check,
    JuraMachineStateUnit::None,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::No,
    JuraMachineSubsystemAttributeType::ServiceRecommendation,
    JuraMachineSubsystem::Thermoblock,
    JuraEntityNonvolatile::No,
    0 /* default value */
  }
};  

/*

  name:         JuraMachineFunctionEntityConfiguration
  type:         enum
  description:  this enum identifies callbacks

*/

static const JuraMachineFunctionEntityConfiguration JuraMachineFunctionEntityConfigurations[] = {
  {
    JuraFunctionIdentifier::PowerOff, 
    NAME_PREFIX "Power Off",
    ENTITY_PREFIX "power_off",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "power_off",
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::No, /* recommend do not use; turns off control board; power board not turned off directly; will only turn on the control board; leads to power board failure notice */
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_01,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Controller,
    JuraMachineReadyState::None,
  },
  {
    JuraFunctionIdentifier::ConfirmDisplayPrompt, 
    NAME_PREFIX "Confirm Display Prompt",
    ENTITY_PREFIX "confirm_display_prompt",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "confirm_display_prompt",
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_02,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Controller,
    JuraMachineReadyState::None,
  },
  {
    JuraFunctionIdentifier::SettingsMenu, 
    NAME_PREFIX "Settings Menu",
    ENTITY_PREFIX "settings_menu",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "settings_menu",
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_03,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Controller,
    JuraMachineReadyState::None,
  },
  {
    JuraFunctionIdentifier::SelectMenuItem, 
    NAME_PREFIX "Select Menu Item",
    ENTITY_PREFIX "select_menu_item",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "select_menu_item",
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_04,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Controller,
    JuraMachineReadyState::None,
  },
  {
    JuraFunctionIdentifier::RotaryRight, 
    NAME_PREFIX "Rotary Right",
    ENTITY_PREFIX "rotary_right",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "rotary_right",
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_05,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Controller,
    JuraMachineReadyState::None,
  },
  {
    JuraFunctionIdentifier::RotaryLeft, 
    NAME_PREFIX "Rotary Left",
    ENTITY_PREFIX "rotary_left",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "rotary_left",
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_06,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Controller,
    JuraMachineReadyState::None,
  },
  {
    JuraFunctionIdentifier::MakeEspresso, 
    NAME_PREFIX "Make Espresso",
    ENTITY_PREFIX "make_espresso",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "make_espresso",
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_07,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Controller,
    JuraMachineReadyState::EspressoReady,
  },
  {
    JuraFunctionIdentifier::MakeCappuccino, 
    NAME_PREFIX "Make Cappuccino",
    ENTITY_PREFIX "make_cappuccino",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "make_cappuccino",
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_08,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Controller,
    JuraMachineReadyState::CappuccinoReady,
  },
  {
    JuraFunctionIdentifier::MakeCoffee, 
    NAME_PREFIX "Make Coffee",
    ENTITY_PREFIX "make_coffee",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "make_coffee",
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_09,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Controller,
    JuraMachineReadyState::CoffeeReady,
  },
  {
    JuraFunctionIdentifier::MakeMacchiato, 
    NAME_PREFIX "Make Macchiato",
    ENTITY_PREFIX "make_macchiato",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "make_macchiato",
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::No,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_0A,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Controller,
    JuraMachineReadyState::MacciattoReady,
  },
  {
    JuraFunctionIdentifier::MakeHotWater, 
    NAME_PREFIX "Make Hot Water",
    ENTITY_PREFIX "make_hot_water",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "make_hot_water",
    JuraMachineStateIcon::Water,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_0B,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Water,
    JuraMachineReadyState::HotWaterReady,
  },
  {
    JuraFunctionIdentifier::MakeMilkFoam, 
    NAME_PREFIX "Make Milk Foam",
    ENTITY_PREFIX "make_milk_foam",
    MQTT_ROOT MQTT_SUBTOPIC_FUNCTION "make_milk_foam",
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::FA_0C,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Milksystem,
    JuraMachineReadyState::MilkFoamReady,
  },
  {
    JuraFunctionIdentifier::MenuSelectRinseBrewGroup, 
    NAME_PREFIX "Rinse Brew Group",
    ENTITY_PREFIX "rinse_brew_group",
    MQTT_ROOT MQTT_SUBTOPIC_MENU,
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::None,
    JuraMachineMenuCommand::Rinse,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::BrewGroup,
    JuraMachineReadyState::RinseBrewGroupComplete,
  },
  {
    JuraFunctionIdentifier::MenuSelectRinseMilkSystem, 
    NAME_PREFIX "Rinse Milk System",
    ENTITY_PREFIX "rinse_milk_system",
    MQTT_ROOT MQTT_SUBTOPIC_MENU,
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::None,
    JuraMachineMenuCommand::MRinse,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Milksystem,
    JuraMachineReadyState::RinseMilkSystemComplete,
  },
  {
    JuraFunctionIdentifier::MenuSelectCleanMilkSystem, 
    NAME_PREFIX "Clean Milk System",
    ENTITY_PREFIX "clean_milk_system",
    MQTT_ROOT MQTT_SUBTOPIC_MENU,
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::None,
    JuraMachineMenuCommand::MClean,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Milksystem,
    JuraMachineReadyState::CleanMilkSystemComplete,
  },
  {
    JuraFunctionIdentifier::MenuSelectCleanBrewGroup, 
    NAME_PREFIX "Clean Brew Group",
    ENTITY_PREFIX "clean_brew_group",
    MQTT_ROOT MQTT_SUBTOPIC_MENU,
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::None,
    JuraMachineMenuCommand::Clean,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::BrewGroup,
    JuraMachineReadyState::CleanBrewGroupComplete,
  },
  {
    JuraFunctionIdentifier::RefreshMQTTConfiguration, 
    NAME_PREFIX "Refresh MQTT Configuration",
    ENTITY_PREFIX "refresh_configuration",
    MQTT_ROOT MQTT_CONFIG_SEND,
    JuraMachineStateIcon::Coffee,
    JuraEntityEnabled::Yes,
    JuraEntitySerialPrintable::Yes,
    JuraEntityAvailabilityFollowsReadyState::Yes,
    JuraServicePortCommand::None,
    JuraMachineMenuCommand::None,
    JuraMachineSubsystemAttributeType::Function,
    JuraMachineSubsystem::Controller,
    JuraMachineReadyState::None,
  }
};

#endif